# Generated by Django 3.1.3 on 2024-02-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart_p',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=159)),
                ('mname', models.CharField(max_length=159)),
                ('totcost', models.FloatField()),
                ('count', models.IntegerField()),
                ('pemail', models.CharField(max_length=159)),
            ],
        ),
        migrations.CreateModel(
            name='cart_u',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=159)),
                ('drugname', models.CharField(max_length=159)),
                ('mname', models.CharField(max_length=159)),
                ('cost', models.FloatField()),
                ('totcost', models.FloatField()),
                ('count', models.IntegerField()),
                ('pharmacy', models.CharField(max_length=159)),
                ('pemail', models.CharField(max_length=159)),
                ('email', models.CharField(max_length=159)),
                ('stz', models.CharField(max_length=159)),
            ],
        ),
        migrations.CreateModel(
            name='drug',
            fields=[
                ('did', models.CharField(max_length=159, primary_key=True, serialize=False)),
                ('drugname', models.CharField(max_length=159)),
                ('mname', models.CharField(max_length=159)),
                ('typ_e', models.CharField(max_length=159)),
                ('uses', models.CharField(max_length=159)),
                ('instructions', models.CharField(max_length=159)),
                ('cost', models.FloatField()),
                ('mrp', models.FloatField()),
                ('cname', models.CharField(max_length=159)),
                ('cemail', models.CharField(max_length=159)),
                ('stock', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='drugstock_p',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=159)),
                ('drugname', models.CharField(max_length=159)),
                ('mname', models.CharField(max_length=159)),
                ('typ_e', models.CharField(max_length=159)),
                ('uses', models.CharField(max_length=159)),
                ('instructions', models.CharField(max_length=159)),
                ('cost', models.FloatField()),
                ('mrp', models.FloatField()),
                ('pname', models.CharField(max_length=159)),
                ('pemail', models.CharField(max_length=159)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='manufacturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=159)),
                ('email', models.CharField(max_length=159)),
                ('pass_word', models.CharField(max_length=159)),
                ('city', models.CharField(max_length=159)),
                ('address', models.CharField(max_length=159)),
                ('stz', models.CharField(max_length=159)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=159)),
                ('email', models.CharField(max_length=159)),
                ('pass_word', models.CharField(max_length=159)),
                ('city', models.CharField(max_length=159)),
                ('address', models.CharField(max_length=159)),
                ('phone', models.CharField(max_length=159)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=159)),
                ('email', models.CharField(max_length=159)),
                ('pass_word', models.CharField(max_length=159)),
                ('phone', models.CharField(max_length=159)),
                ('city', models.CharField(max_length=159)),
                ('gender', models.CharField(max_length=159)),
            ],
        ),
    ]
